export { default as logo } from './logo.svg'
export { default as slider } from './slider-img.png'
export { default as mobilePhone } from './Mobile Phone.png'
export { default as smartWatch } from './smart watch.png'
export { default as Headphone } from './headphone.png'
export { default as cpuHeat } from './cpu.png'
export { default as tp1 } from './tp1.jpg'
export { default as tp2 } from './tp2.jpg'
export { default as tp3 } from './tp3.jpg'
export { default as tp4 } from './tp4.jpg'
export { default as tp5 } from './tp5.jpg'
export { default as tp6 } from './tp6.png'
export { default as tp7 } from './tp7.jpg'
export { default as tp8 } from './tp8.jpg'
